name: GitHub Actions Version

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.x


jobs:
  versions:
    name: "Versions"
    runs-on: windows-latest

    steps:
      - name: .NET
        run: dotnet --version
